import { Plugin } from '@hykord/structures';
import { BetterSet } from '../utils';
export declare const plugins: BetterSet<Plugin>;
export declare const directory: string;
export declare const load: () => Promise<void>;
export declare const init: () => Promise<void>;
export declare const addPlugin: (plugin: Plugin) => Promise<void>;
export declare const enablePlugin: (plugin: Plugin) => Promise<void>;
export declare const disablePlugin: (plugin: Plugin) => Promise<void>;
export declare const removePlugin: (plugin: Plugin) => Promise<void>;
export declare const togglePlugin: (plugin: Plugin) => Promise<void>;
