import { Theme } from '@hykord/structures';
import { BetterSet } from '../utils';
import type { ITheme } from '@hykord/structures/Theme';
export declare const themes: BetterSet<ITheme>;
export declare const directory: string;
export declare const loadQuickCss: () => Promise<void>;
export declare const init: () => void;
export declare const addTheme: (theme: Theme) => Promise<void>;
export declare const enableTheme: (theme: Theme) => void;
export declare const disableTheme: (theme: Theme) => void;
export declare const removeTheme: (theme: Theme) => Promise<void>;
export declare const toggleTheme: (theme: Theme) => void;
