export declare enum HykordIpcEvents {
    'GET_SETTING_SYNC' = "HYKORD_GET_SETTING_SYNC",
    'GET_SETTING' = "HYKORD_GET_SETTING",
    'SET_SETTING_SYNC' = "HYKORD_SET_SETTING_SYNC",
    'SET_SETTING' = "HYKORD_SET_SETTING",
    'DELETE_SETTING' = "HYKORD_DELETE_SETTING",
    'ADD_VALUE_TO_SETTING_SYNC' = "HYKORD_ADD_VALUE_TO_SETTING_SYNC",
    'ADD_VALUE_TO_SETTING' = "HYKORD_ADD_VALUE_TO_SETTING",
    'REMOVE_VALUE_FROM_SETTING_SYNC' = "HYKORD_REMOVE_VALUE_FROM_SETTING_SYNC",
    'REMOVE_VALUE_FROM_SETTING' = "HYKORD_REMOVE_VALUE_FROM_SETTING",
    'SAVE_SETTINGS' = "HYKORD_SAVE_SETTINGS",
    'RELAUNCH_APP' = "HYKORD_RELAUNCH_APP",
    'GET_REPOSITORY' = "HYKORD_GET_REPOSITORY",
    'GET_LATEST_COMMIT_HASH' = "HYKORD_GET_LATEST_COMMIT_HASH",
    'CHECK_FOR_UPDATES' = "HYKORD_CHECK_FOR_UPDATES",
    'DOWNLOAD_UPDATE' = "HYKORD_DOWNLOAD_UPDATE"
}
export declare type KnownSettings = 'hykord.quick-css' | 'hykord.react-devtools' | 'hykord.disable-science-requests' | 'hykord.unsafe-require' | 'hykord.enabled.themes' | 'hykord.enabled.plugins' | string;
