import { injectCss } from "@hykord/patcher";

export default () => {
    injectCss('.hykord-errorboundary{font-family: var(--font-display);color:var(--text-normal);padding:16px}.hykord-errorboundary-code{background-color:var(--background-secondary);font-family:var(--font-code);user-select:text}'); // For ErrorBoundary

    injectCss('.hykord-card{padding: 16px;margin-bottom: 10px;}.hykord-form-divider{margin-top:10px;margin-bottom:10px}'); // Simple CSS - Add padding for plugin card & margin for divider

    injectCss('.hykord-textinput-container{border-radius:4px;overflow:hidden}.hykord-textinput-container,.hykord-textinput-inner{-webkit-box-sizing:border-box;box-sizing:border-box;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-flex:1;-ms-flex:1 1 auto;flex:1 1 auto}.hykord-textinput-inner{position:relative;-webkit-box-orient:horizontal;-webkit-box-direction:normal;-ms-flex-direction:row;flex-direction:row;-ms-flex-wrap:wrap;flex-wrap:wrap;padding:1px;min-width:0;-webkit-box-align:center;-ms-flex-align:center;align-items:center}.hykord-textinput-input{-webkit-box-sizing:border-box;box-sizing:border-box;background:transparent;border:none;resize:none;-webkit-box-flex:1;-ms-flex:1;flex:1;min-width:48px;margin:1px;-webkit-appearance:none;-moz-appearance:none;appearance:none}')
    // Grabbed from discord from searchbar, because doesn't work :( ^

    injectCss('.theme-dark{--toast-background:#2f3136;--toast-header:#202225;--toast-contents:#36393f;--toast-box-shadow:rgba(0, 0, 0, .2);--toast-border:rgba(28, 36, 43, .6)}.theme-light{--toast-background:#fff;--toast-header:#e3e5e8;--toast-contents:#f2f3f5;--toast-box-shadow:rgba(0, 0, 0, .1);--toast-border:rgba(28, 36, 43, .06)}.hykord-toasts-container{display:flex;flex-direction:column;align-items:flex-end;justify-content:flex-end}.hykord-toast{display:flex;flex-direction:column;background-color:var(--toast-background);border:1px solid var(--toast-border);box-shadow:0 2px 10px 0 var(--toast-box-shadow);box-sizing:border-box;border-radius:5px;position:absolute;animation:.5s slide-in,1.4s cubic-bezier(.36,.07,.19,.97) both shake;max-width:600px;min-width:223px;width:320px;right:25px;bottom:25px;z-index:999}.hykord-toast .header{display:flex;color:var(--text-normal);font-weight:600;font-size:16px;line-height:19px;background-color:var(--toast-header);box-shadow:0 2px 3px 0 var(--toast-box-shadow);border-radius:5px 5px 0 0;padding:12px 20px}.hykord-toast .header .icon{margin-right:5px}.hykord-toast .header .icon img{width:18px;height:18px}.hykord-toast .header .dismiss{width:16px;height:16px;opacity:.5;transition:opacity .2s;margin-left:auto;cursor:pointer;font-size:12px;padding:1px}.hykord-toast .buttons button[class*=lookGhost-]:hover,.hykord-toast .header .dismiss:hover{opacity:1}.hykord-toast .contents{display:flex;border-radius:0 0 5px 5px;text-align:center;justify-content:flex-end;flex-direction:column;padding:10px 10px 0}.hykord-toast .contents .inner{color:var(--text-normal);font-size:14px;line-height:16px;background-color:var(--toast-contents);border:2px solid var(--toast-border);border-radius:5px;padding:10px 6px;margin:0 0 6px}.hykord-toast .buttons{box-sizing:border-box;flex-wrap:wrap;display:flex;width:100%;padding:10px}.hykord-toast .buttons button{box-sizing:border-box;min-width:calc(50% - 10px);padding:1.5%;margin:1.5% 3px;flex:1}.hykord-toast .buttons button[class*=lookGhost-]{opacity:.8;transition:background-color .17s,color .17s,opacity .17s,-webkit-transform .17s}.hykord-toast .contents+.buttons{padding-top:0}.hykord-toast.leaving{animation:.7s ease-out slide-out}.theme-light .hykord-toast{border:1px solid rgba(191,191,191,.3)}.hykord-toast[data-toast-type=info] .icon{color:#7289da}.hykord-toast[data-toast-type=warning] .icon{color:#faa61a}.hykord-toast[data-toast-type=danger] .icon{color:#f04747}.hykord-toast[data-toast-type=success] .icon{color:#43b581}@keyframes shake{10%,90%{transform:translate3d(1px,0,0)}20%,80%{transform:translate3d(2px,0,0)}30%,50%,70%{transform:translate3d(-4px,0,0)}40%,60%{transform:translate3d(4px,0,0)}}@keyframes slide-in{from{margin-right:-500px;opacity:0}}@keyframes slide-out{to{margin-right:-500px;opacity:0}}');
    // Grabbed from https://github.com/powercord-org/powercord/blob/v2/src/Powercord/plugins/pc-notices/style.scss

    const fontAwesome = Object.assign(
        document.createElement('link'),
        {
            rel: 'stylesheet',
            href: 'https://kit-pro.fontawesome.com/releases/v5.15.4/css/pro.min.css'
        }
    );

    document.head.appendChild(fontAwesome);
}