import './modules/webpack/patch';
import './polyfill';
import './loaders';
export declare const version: string;
export declare const gitHash: string;
export declare const directory: string;
export * as Utils from './utils';
export * as Webpack from '@hykord/webpack';
export * as Components from '@hykord/components';
export * as Structures from '@hykord/structures';
export * as Apis from '@hykord/apis';
export * as Patcher from '@hykord/patcher';
export * as Loaders from './loaders';
