import { ModuleExports, WebpackChunkGlobal, RawModule, Filter, LazyCallback } from '@common';
export declare const subscriptions: Map<Filter, LazyCallback>;
export declare function _initWebpack(webpackChunk: WebpackChunkGlobal): void;
export declare const getRawModules: () => RawModule[];
export declare const getAllModules: (filter?: Filter | undefined) => ModuleExports[];
export declare const getModule: (filter?: Filter | undefined) => ModuleExports | null;
export declare const getAllByProps: (...props: string[]) => ModuleExports[];
export declare const getByProps: (...props: string[]) => ModuleExports | null;
export declare const getAllByPrototypeFields: (...protos: string[]) => ModuleExports[];
export declare const getByPrototypeFields: (...protos: string[]) => ModuleExports | null;
export declare const getAllByCode: (...code: string[]) => ModuleExports[];
export declare const getByCode: (...code: string[]) => ModuleExports | null;
export declare function waitFor(filter: string | string[] | Filter, callback: LazyCallback): void;
