name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # For setup
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1

      - name: Setup Bun
        uses: xhyrom/setup-bun@v0.1.7
        if: matrix.os != 'windows-latest'
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Uname
        if: matrix.os != 'windows-latest'
        run: uname -a

      - name: Init
        run: make init

      # Build
      - name: Build installer
        run: make build-installer
      
      - name: Upload installer Linux/MacOS
        uses: actions/upload-artifact@v3
        if: matrix.os != 'windows-latest'
        with:
          name: installer-${{ matrix.os }}-amd64
          path: packages/installer/zig-out/bin/installer

      - name: Upload installer Windows
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: installer-${{ matrix.os }}-amd64
          path: packages/installer/zig-out/bin/installer.exe

      - name: Build injector
        run: make build-injector
      
      - name: Upload injector Linux/MacOS
        uses: actions/upload-artifact@v3
        if: matrix.os != 'windows-latest'
        with:
          name: injector-${{ matrix.os }}-amd64
          path: packages/injector/zig-out/bin/injector

      - name: Upload injector Windows
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: injector-${{ matrix.os }}-amd64
          path: packages/injector/zig-out/bin/injector.exe

      - name: Build hykord
        if: matrix.os == 'ubuntu-latest'
        run: make build-hykord

      - name: Upload hykord Linux
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: hykord
          path: packages/hykord/dist/

  release:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*"
          draft: true
          tag: canary

      - run: ls artifacts/*

      - name: Push to branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: hykord-dist
          folder: ./artifacts/hykord
